{{- if and (.Values.awsCsiProvider) (.Values.awsCsiProvider.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  {{ if .Values.env }}
  name: {{ .Values.env }}-aws-secrets-csi-provider
  {{ else }}
  name: aws-secrets-csi-provider
  {{ end }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io    
spec:
  project: default
  source:
    repoURL: {{ .Values.repoUrl }}
    path: add-ons/aws-csi-secrets-provider
    targetRevision: {{ .Values.targetRevision }}
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true    
    retry:
      limit: 1
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 1m  
{{- end -}}