{{- if and (.Values.awsCsiProvider) (.Values.awsCsiProvider.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-secrets-csi-provider 
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io    
spec:
  project: default
  source:
    repoURL: {{ .Values.repoUrl }}
    path: add-ons/aws-csi-secrets-provider
    targetRevision: {{ .Values.targetRevision }}
  destination:
    server: {{ .Values.destination.server }}
    namespace: kube-system
    name: {{ .Values.destination.name }}
  syncPolicy:
    automated:
      prune: true    
    retry:
      limit: 1
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 1m  
{{- end -}}