{{- if and (.Values.metricsServer) (.Values.metricsServer.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.env }}metrics-server 
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io    
spec:
  project: default
  source:
    repoURL: {{ .Values.repoUrl }}
    path: add-ons/metrics-server
    targetRevision: {{ .Values.targetRevision }}
  destination:
    {{ if .Values.destination.server }} server: {{ .Values.destination.server }} {{ end }}
    {{ if .Values.destination.name }} name: {{ .Values.destination.name }} {{ end }}
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true    
    retry:
      limit: 1
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 1m  
{{- end -}}