apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-secrets-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-secrets-sync
  template:
    metadata:
      labels:
        app: dummy-secrets-sync
    spec:
      serviceAccountName: {{.Values.atlantis.serviceAccount.name}}
      containers:
      - name: dummy-secrets-sync
        image: k8s.gcr.io/echoserver:1.4
        volumeMounts:
          - name: atlantis-github-config
            mountPath: "/mnt/atlantis-github-config"
            readOnly: true
        env:
          - name: test_env
            valueFrom:
              secretKeyRef:
                name: atlantis-github-secrets
                key: github_secret
          - name: test_env_2
            valueFrom:
              secretKeyRef:
                name: atlantis-github-secrets
                key: github_token
      volumes:
        - name: atlantis-github-config
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: aws-secret-atlantis-github-secrets