apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: atlantis-role
rules:
  - apiGroups:
        - ""
        - apps
        - autoscaling
        - batch
        - extensions
        - policy
        - rbac.authorization.k8s.io
    resources:
      - pods
      - componentstatuses
      - configmaps
      - daemonsets
      - deployments
      - events
      - endpoints
      - horizontalpodautoscalers
      - ingress
      - jobs
      - limitranges
      - namespaces
      - nodes
      - pods
      - persistentvolumes
      - persistentvolumeclaims
      - resourcequotas
      - replicasets
      - replicationcontrollers
      - serviceaccounts
      - services
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: atlantis-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: atlantis-role 
subjects:
  kind: ServiceAccount
  name: {{.Values.atlantis.serviceAccount.name}} 