apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secret-atlantis-github-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: atlantis-github-config
        objectType: "secretsmanager"
        jmesPath:
          - path: github_token
            objectAlias: githubToken
          - path: github_secret
            objectAlias: githubSecret
  # Create k8s secret. It requires volume mount first in the pod and then sync.
  secretObjects:                
    - secretName: atlantis-github-secrets
      type: Opaque
      data:
        - objectName: githubSecret
          key: github_secret
        - objectName: githubToken
          key: github_token
