apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secret-atlantis-github-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: /{{ .Values.env }}/atlantis/github-config
        objectType: "secretsmanager"
  # Create k8s secret. It requires volume mount first in the pod and then sync.
  secretObjects:                
    - secretName: atlantis-github-secrets
      type: Opaque
      data:
        - objectName: /{{ .Values.env }}/atlantis/github-config
          key: key1
