apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-atlantis-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: {{ .Values.awsSecretName }}
        objectType: "secretsmanager"
        jmesPath:
          - path: github_token
            objectAlias: githubtoken
          - path: github_secret
            objectAlias: githubsecret
  # Create k8s secret. It requires volume mount first in the pod and then sync.
  secretObjects:                
    - secretName: atlantis-github-secrets
      type: Opaque
      data:
        - objectName: githubsecret
          key: github_secret
        - objectName: githubtoken
          key: github_token


