atlantis:
  image:
    repository: jamorosocaylent/atlantis-aws-cli
    tag: latest
  github:
    user: 
  vcsSecretName: atlantis-github-secrets
  ingress:
    annotations: {
      alb.ingress.kubernetes.io/scheme: internet-facing,
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443},{"HTTP":80}]',
      alb.ingress.kubernetes.io/ssl-redirect: '443',
      external-dns.alpha.kubernetes.io/hostname: ,
      alb.ingress.kubernetes.io/group.name: ci-cd-ingress,
      kubernetes.io/ingress.class: alb
    }
    host: 
    tls:
      - hosts:
        - 
  repoConfig: |
    ---
    repos:
    - id: /.*/
      apply_requirements: [approved, mergeable]
      allowed_overrides: [apply_requirements, workflow]
      allow_custom_workflows: true
  orgAllowlist: 
  storageClassName: gp2
env: dev
awsSecretName: 
